run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - unconvert
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G204 # Subprocess launched with variable (needed for player launcher)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
